### ISSUE TITLE
Make C-Reduce release for LLVM/Clang 7.0

### ISSUE THREAD

**Issue by eeide** [csmith-project/creduce#171]
Shortly after LLVM 7.0 is officially released, make an official C-Reduce release that uses/requires LLVM 7.0.

LLVM 7.0.0 was released today, Wed Sep 19 2018.

**Comment by marxin** [comment]
Using ```./configure``` I see following errors:

```
make[2]: Entering directory '/home/marxin/Programming/creduce/clang_delta'
g++ -DHAVE_CONFIG_H -I. -I..   -I"/usr/include/clang"  -I/usr/include -D_FORTIFY_SOURCE=0 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -fno-strict-aliasing -fPIC -fvisibility-inlines-hidden -std=c++11 -ffunction-sections -fdata-sections -DNDEBUG -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -fno-exceptions -g -O3 -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -MT clang_delta-ExpressionDetector.o -MD -MP -MF .deps/clang_delta-ExpressionDetector.Tpo -c -o clang_delta-ExpressionDetector.o `test -f 'ExpressionDetector.cpp' || echo './'`ExpressionDetector.cpp
g++ -DHAVE_CONFIG_H -I. -I..   -I"/usr/include/clang"  -I/usr/include -D_FORTIFY_SOURCE=0 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -fno-strict-aliasing -fPIC -fvisibility-inlines-hidden -std=c++11 -ffunction-sections -fdata-sections -DNDEBUG -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -fno-exceptions -g -O3 -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -MT clang_delta-RemoveUnusedEnumMember.o -MD -MP -MF .deps/clang_delta-RemoveUnusedEnumMember.Tpo -c -o clang_delta-RemoveUnusedEnumMember.o `test -f 'RemoveUnusedEnumMember.cpp' || echo './'`RemoveUnusedEnumMember.cpp
g++ -DHAVE_CONFIG_H -I. -I..   -I"/usr/include/clang"  -I/usr/include -D_FORTIFY_SOURCE=0 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -fno-strict-aliasing -fPIC -fvisibility-inlines-hidden -std=c++11 -ffunction-sections -fdata-sections -DNDEBUG -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -fno-exceptions -g -O3 -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -MT clang_delta-TransformationManager.o -MD -MP -MF .deps/clang_delta-TransformationManager.Tpo -c -o clang_delta-TransformationManager.o `test -f 'TransformationManager.cpp' || echo './'`TransformationManager.cpp
TransformationManager.cpp: In member function ‘llvm::raw_ostream* TransformationManager::getOutStream()’:
TransformationManager.cpp:226:42: error: ‘F_RW’ is not a member of ‘llvm::sys::fs’
       OutputFileName, EC, llvm::sys::fs::F_RW);
                                          ^~~~
make[2]: *** [Makefile:1929: clang_delta-TransformationManager.o] Error 1
RemoveUnusedEnumMember.cpp: In member function ‘void RemoveUnusedEnumMember::removeEnumConstantDecl()’:
RemoveUnusedEnumMember.cpp:103:36: error: conversion from ‘clang::CharSourceRange’ to non-scalar type ‘std::pair<clang::SourceLocation, clang::SourceLocation>’ requested
       SrcManager->getExpansionRange(StartLoc);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
RemoveUnusedEnumMember.cpp:109:36: error: conversion from ‘clang::CharSourceRange’ to non-scalar type ‘std::pair<clang::SourceLocation, clang::SourceLocation>’ requested
       SrcManager->getExpansionRange(EndLoc);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
ExpressionDetector.cpp:62:16: error: ‘virtual void {anonymous}::IncludesPPCallbacks::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*)’ marked ‘override’, but does not override
   virtual void InclusionDirective(SourceLocation HashLoc,
                ^~~~~~~~~~~~~~~~~~
```

**Comment by eeide** [comment]
There is currently an `llvm-7.0` branch in the C-Reduce repository. Do the errors above occur on that branch?

**Comment by chenyang78** [comment]
Hi Marxin,

I think these issues have been fixed in our llvm 7.0 branch. Thanks!

- Yang

**Comment by marxin** [comment]
I can confirm the branch works and I also tested creduce on a real reduction and it looks fine.
Can you please create a pull request for it?

**Comment by chenyang78** [comment]
@marxin, I think @eeide will work on a new release for LLVM 7.0 when he has bandwidth. Thanks for checking that!

**Comment by eeide** [comment]
The official release that supports LLVM 7 is available now: **C-Reduce 2.9.0**

Commit 0fc288e, tag `creduce-2.9.0`.
Find the release here: https://github.com/csmith-project/creduce/releases/tag/creduce-2.9.0
